forge_cmd_env() {
  local service_file
  local module_name
  local module_dir
  local env_file
  local sep
  local tmp_output

  sep='------------------------------------------------------------'
  tmp_output="$(mktemp "${ENV_OUTPUT_FILE}.tmp.XXXXXX")"

  {
    printf '# Generated by Forge\n'

    while IFS= read -r service_file; do
      [[ -z "$service_file" ]] && continue
      module_name="$(basename "$service_file" .yml)"
      module_dir="$(find_module_dir "$module_name")" || continue
      env_file="$module_dir/env.example"
      [[ ! -f "$env_file" ]] && continue

      printf '\n'
      printf '# %s\n' "$sep"
      printf '# %s\n' "$module_name"
      printf '# %s\n' "$sep"
      cat "$env_file"
    done < <(find_project_service_files)
  } > "$tmp_output"

  mv "$tmp_output" "$ENV_OUTPUT_FILE"

  echo "Wrote $ENV_OUTPUT_FILE"
}