forge_cmd_env() {
  local env_file
  local module_name
  local tmp_output

  tmp_output="$(mktemp "${ENV_OUTPUT_FILE}.tmp.XXXXXX")"

  {
    echo "# Generated by Forge"
    echo "# Copy this file to .env and update values."
    echo

    while IFS= read -r env_file; do
      [[ -z "$env_file" ]] && continue
      module_name="$(basename "$env_file" .env.example)"

      echo "# $module_name"
      cat "$env_file"
      echo
    done < <(find_project_env_files)
  } > "$tmp_output"

  mv "$tmp_output" "$ENV_OUTPUT_FILE"

  echo "Wrote $ENV_OUTPUT_FILE"
}